name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: windows-2025-vs2026
            target: x86_64-pc-windows-msvc
            ext: ".exe"
          - os: macos-26
            target: aarch64-apple-darwin
            ext: ""

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: cargo build --release --locked

      - name: Rename binary
        shell: bash
        run: |
          mv target/release/lister${{ matrix.ext }} \
             lister-${{ matrix.target }}${{ matrix.ext }}

      - uses: softprops/action-gh-release@v2
        with:
          files: lister-*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}