name: Release

on:
  push:
    tags:
      - "v*.*.*" # triggers only when you push tags like v1.0.0

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build Windows binary with cross
        run: cross build --release --target x86_64-pc-windows-gnu

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-pc-windows-gnu/release/lister.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}